dependencies {
  implementation project(":java-ta")
 
  // openflexo dep
  implementation group: 'junit', name: 'junit', version: '4.13.2'

 // TODO: why should i mention it here ? Shouldn't i inherit this dependency transitively from java-ta ?
  //implementation group: 'fr.inria.gforge.spoon', name: 'spoon-core', version: '11.0.1-beta-2'
  implementation group: 'fr.inria.gforge.spoon', name: 'spoon-core', version: '9.1.0'

  // testing dep
  testImplementation flexoFoundation()
  testImplementation flexoFoundationTest()

  // Test resource center
  testRuntimeOnly project(':java-ta-test-rc')
}
